### ISSUE TITLE
Pipeline to include Javascript function triggers

### ISSUE THREAD

**Issue by jklingen92** [Kurohyou/Roll20-Snippets#12]
I've been reading the blog posts and combing through the code, working to build out my own sheet. It's been very challenging to understand what the pipelines are here, namely, how does the javascript actually get attached and to where. Roll20 seems to have a lot of poorly documented requirements (i.e. apparently all JS must be organized into on sheetworker, or something). 

My biggest question is what are triggers and how do they work? It looks like there are a number of different types of triggers (affects, calculation, listeners, etc). Are those documented anywhere? There's some code in here that "registers" functions to kFuncs, although that's not listed in the README anywhere as a necessary step. Does the code that handles triggers look for those triggers in kFuncs? The return statement for kFuncs is in a different file from the initialization, which makes it very hard to read.

Here's my main pug file:
```
// system.pug
include scaffold/_kpug.pug

mixin spec-block(name)
    .spec
    // Displays modifier
    +span({
      name: `${name}_mod`, 
      title:`@{${name}_mod}`,
      value: 0,
      trigger: {calculation: "calculateSpecMod"}
    }) 
    // Base input
    +number({
      name, 
      class: "base-input",
      value: 10,
      trigger: {affects: [`${name}_mod`]}
    })

main
  .sheet
    .specs
      for spec in constants.specs 
        +spec-block(spec)

+kscript
  include javascript/specs.js
 ```
 and 
```
// javascript/specs.js

 function calculateSpecMod(spec) {
  console.log("hello world")
  return Math.floor((spec - 10) / 2)
}
```
I haven't been able to see any console output anywhere or values change based on updating anything. I've also been unable to see any of the hefty js that kscript generates show up in the actual character sheet sandbox, despite it being visible in the HTML files. It's like its being stripped from the file when its uploaded.

UPDATE: It appears that the kscript code is crashind that's likely the cause of the problem. I've downloaded the most recent scaffold code from week 4 (see issue #15). I put in a PR for a bug that seems to only exist in older versions of the code (#14 , and again #15), but I'm still seeing an error message in the console when loading the kscript:
`SyntaxError: unexpected token: identifier`

**Comment by Kurohyou** [comment]
Hi Jake,

Thanks for following along! Yes, I've used an updated version of the K-scaffold in later blog entries. I'm working on getting that updated scaffold ready for a full release.

For your question about triggers:

A trigger is an object that describes how the K-scaffold should resolve changes to that attribute. The possible properties of the trigger object when you put it in an element mixin (like `+number()` or `+span()`) are:

- **affects**: An array of attributes that are affected when this attribute changes.
- **calculation**: The name of a function that calculates the value of an attribute. Only called if the attribute is updated via the script.
- **initialFuncs**: A function that is called when this attribute is changed by the user (as opposed to being updated by the script)
- **listenerFunc**: A function that is called directly in response to the attribute being changed or the button being clicked. Replaces the K-scaffold's default listener function, `accessSheet()`.
- **triggeredFuncs**: An array of function names that are called when the attribute is changed by the user or is affected by another attribute. Similar to `calculation`, but can hold multiple functions and can do more complex things as triggeredFuncs shouldn't return a value other than `undefined`.

The content of each of these (or the content of their arrays) are strings. A trigger for a given attribute can have any number of these. The order of calls for a given attribute is `initialFunc`, `triggeredFuncs` (in array order), `calculation`.

Apparently I forgot to describe the trigger object in any of the documentation, so thank you for asking the question! Gonna leave this open until I get the documentation updated with the above.

Scott

**Comment by Kurohyou** [comment]
Documentation and code are now updated to the most recent version of the K-scaffold.
