### ISSUE TITLE
Multiple copies of the same code

### ISSUE THREAD

**Issue by jklingen92** [Kurohyou/Roll20-Snippets#15]
Its a bit difficult to navigate the code on this repository because there are several different versions of the code, corresponding to the different blog posts. There are a few things that you could do keep them separate without creating so many redundancies:

1. You could give them separate branches. This would require users who wanted to get one or the other to understand how to checkout different branches. You would be able to push fixes to earlier versions and propogate those changes to later versions by rebasing (although that would be a bit of a hassle.

2. You could tag them at each release point. This would allow you to keep the history nice and do some development on them. It would be easy to share the links to each release as well. 

3. You could compress the whole repository as a certain point and then upload it as `Blog_Post_1_release.zip` or whatever. This would make it really easy for people to download the release that they want, but it would be impossible to maintain a specific release, unless you combined this strategy with one of the above.

**Comment by Kurohyou** [comment]
Thanks for the suggestions Jake, I'll take a look at better ways to organize things. I'm working on some edits to the scaffold itself as well, which is also why the latest blog post is delayed.
