### ISSUE TITLE
[k-Scaffold] `+roller` doesn't work if `name` contains `"roll`"

### ISSUE THREAD

**Issue by Riernar** [Kurohyou/Roll20-Snippets#26]
When using the `+roller` mixin, if the provided `name` contains the string `"roll"` somewhere, the roll button no longer works (it doesn't trigger the abilitiy).

### Without `"roll"`
```pug
+roller({name:'testrl')
```
generated HTML
```html
<button class="roller" name="roll_testrl" value="@{testrl_action}" title="%{testrl}" type="roll">
</button>
<button name="act_testrl-action" hidden="" type="action" title="%{testrl-action}">
</button>
<input name="attr_testrl_action" type="hidden" title="@{testrl_action}"/>
```

### With "roll"
```pug
+roller({name:'testroll')
```
```html
<button class="roller" name="roll_testroll" value="@{testaction}" title="%{testroll}" type="roll">
</button>
<button name="act_testaction" hidden="" type="action" title="%{testaction}">
</button>
<input name="attr_testaction" type="hidden" title="@{testaction}"/>
```

**Comment by Kurohyou** [comment]
@Riernar, I can't replicate this on my end. Can you take a look at [tests.pug](https://github.com/Kurohyou/Roll20-Snippets/blob/0-40prep/K_Scaffold/Template%20v2/tests.pug), [tests.html](https://github.com/Kurohyou/Roll20-Snippets/blob/0-40prep/K_Scaffold/Template%20v2/tests.html), and [rollerbughunt.js](https://github.com/Kurohyou/Roll20-Snippets/blob/0-40prep/K_Scaffold/Template%20v2/Javascript/rollerbughunt.js) to see if I've replicated your code correctly?

**Comment by Riernar** [comment]
Your test works properly, and now it also works on my original use-case, I have no idea what I botched
I'm absolutely sorry for wasting your time !
