### ISSUE TITLE
[Suggestion] Repo dedicated to k-scaffold

### ISSUE THREAD

**Issue by Riernar** [Kurohyou/Roll20-Snippets#31]
I propose to dedicate this repository to k-scaffold, by renaming it to `k-scaffold` and changing the layout.

## Rational
The current layout of the repo makes it harder-than-needed to install or add k-scaffold into a project. Other than k-scaffold, this repository containes two snippets `parseRepeatName` and `fill-left` elements, which are already part of k-scaffold.
Making this repo k-scaffold dedicated would make k-scaffold installation easy though a `git clone --depth 1` or `git submodule add`. 

## Propose changes
- Rename the repo to k-scaffold
- Refactor the repo to the following layout:
```
.
├── docs/ # documentation folder
├──tutorial/ # Folder holding the tutorial code and posts
├── src/ # source for k-scaffold
│   ├── buttons/ # a part of k-scaffold, isolated in a folder
│   │   └── _buttons.pug
│   ├── helpers/ # a part of k-scaffold that need .pug, .js and .scss to worl
│   │   ├── helpers.js
│   │   └── _helpers.pug
│   │   └── _helpers.scss
│   └── tabs/  # a part of k-scaffold that need .pug, .js and .scss to worl
│       ├── tabs.js
│       ├── _tabs.pug
│       └── _tabs.scss
├── _kpug.pug # root file to import in a project using k-scaffold
├── _k.scss # root file to import in a project using k-scaffold
├── LICENSE
├── README.md
└── template/ # template character sheet for creating new project
    ├── prepros.config
    ├── sheet.json
    ├── system.html
    ├── system.pug
    └── translation.json
  ```

Installation would be achieved through
```bash
git submodule add <repo url>
```
and allow updating the underlying version of k-scaffold. Submodules also prevent staging k-scaffold files as part of the sheet's repo: git will go get the k-scaffold repo itself and put it in a folder.

EDIT: Added Tutorial folder to grid outline.

**Comment by Kurohyou** [comment]
Agreed. I'd add a root level directory of `tutorial`, or something along those lines as well for the tutorial walkthroughs (which I really need to finish).

**Comment by Kurohyou** [comment]
Particularly like the submodule idea!

**Comment by Riernar** [comment]
I'll make a PR for that and #29 then, they are quite related

**Comment by Kurohyou** [comment]
This will happen with the release of v0.1.0

**Comment by Kurohyou** [comment]
Repo is set up. Code has been migrated. Further development will occur there.
https://github.com/Kurohyou-Studios/k-scaffold/tree/1-0-0-dev
