### ISSUE TITLE
`kTabOnOpen` fails if the sheet contain no tabs

### ISSUE THREAD

**Issue by Riernar** [Kurohyou/Roll20-Snippets#48]
This is either due to a missing `varObjects` prefix in https://github.com/Kurohyou/Roll20-Snippets/blob/c90c954eeceb829363df25b06980b6c6006282bd/K_Scaffold/Template%20v2/scaffold/tabs/tabs.js#L30, or a lack of handling for undefined `persistentTab` because the tab mixin was never called

**Comment by Kurohyou** [comment]
Yep, just added it to the locals definitions so it'll always be defined.

**Comment by Kurohyou** [comment]
Resolved in migrated code
